In [28]:
import tifffile
from PIL import Image
import numpy as np
img = Image.open(r'C:\Users\roumba\Documents\Software\deep-events\original_data\220921_mtstaygold_cos7_iSIM_fl\220921_mtstaygold_cos7_Fluorescent_4.ome.tif')
dataar=np.zeros((100, 1268,1268))

for frame_index in range(100):
    img.seek(frame_index) #starts from 0 I think?
    yl=2048-2000
    yu=1268+yl
    box_a = (512,yl,1780,yu) #choose dimensions of box
    imcrop= img.crop(box_a)
    dataar[frame_index, :, :] = np.array(imcrop)
        

tifffile.imwrite('original_crop.tiff' , (dataar).astype(np.uint16), photometric='minisblack')


In [49]:
img = Image.open(r'C:\Users\roumba\Documents\Software\deep-events\original_data\220921_mtstaygold_cos7_iSIM_fl\220921_mtstaygold_cos7_Fluorescent_4.ome.tif')
data_norm=np.zeros((img.n_frames,2048,2048))
k=0.3
kk=1/(1-k)
data_first=np.zeros((img.n_frames,2048,2048))

for framenumber in range(img.n_frames):
    img.seek(framenumber)
    arrayim=np.array(img)
    data_first[framenumber,:,:]=arrayim
    data = (data_first[framenumber])/255                                            
    data = data-k
    data [data < 0] = 0   
    data_norm[framenumber] = data*kk

import imageio
imageio.mimwrite('original_norm.tiff', (data_norm).astype(np.float64))


In [48]:
import napari
viewer = napari.Viewer()
viewer.add_image(augm)
viewer.add_image(augm_g)

[[[0.30882353 0.28921569 0.32843137 ... 0.32352941 0.28921569 0.26960784]
  [0.35294118 0.24509804 0.30882353 ... 0.30392157 0.26470588 0.28431373]
  [0.34803922 0.29411765 0.31862745 ... 0.28921569 0.29901961 0.26960784]
  ...
  [0.26960784 0.25       0.24509804 ... 0.29411765 0.30392157 0.29901961]
  [0.25490196 0.25490196 0.28431373 ... 0.28921569 0.25980392 0.25980392]
  [0.31862745 0.24509804 0.28921569 ... 0.26470588 0.25490196 0.28431373]]

 [[0.28921569 0.30392157 0.35294118 ... 0.28921569 0.25980392 0.28921569]
  [0.28431373 0.37254902 0.32352941 ... 0.29901961 0.28921569 0.25      ]
  [0.33333333 0.31372549 0.33333333 ... 0.26470588 0.28921569 0.24019608]
  ...
  [0.26470588 0.25490196 0.30882353 ... 0.26470588 0.26960784 0.29411765]
  [0.26960784 0.2745098  0.30392157 ... 0.29411765 0.26470588 0.26960784]
  [0.29411765 0.27941176 0.24509804 ... 0.25980392 0.26470588 0.24019608]]

 [[0.28921569 0.33823529 0.29411765 ... 0.24019608 0.29901961 0.28431373]
  [0.28921569 0.357843